name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Task
        uses: go-task/setup-task@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: task dev:lint
